name: Enable PR Auto-merge

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge when labeled
        if: contains(github.event.pull_request.labels.*.name, 'automerge')
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
